name: example
description: A new Flutter project.

publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.4.0

dependencies:
  rate_limiter:
    path: ../

dependency_overrides:
  rate_limiter:
    path: ../
