name: rate_limiter
description: A pure dart package to apply useful rate limiting strategies on regular functions.
version: 1.0.0
homepage: https://github.com/GetStream/rate_limiter
repository: https://github.com/GetStream/rate_limiter
issue_tracker: https://github.com/GetStream/rate_limiter/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.16.8