name: Dart CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
      - name: Install Dependencies
        run: flutter pub get
      - name: Format
        run: flutter format --set-exit-if-changed .
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test --no-pub --coverage
      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          min_coverage: 97
          path: "./coverage/lcov.info"
      - name: Report CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info